# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Yoda\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_EVENT_CREATE, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        our_database_users:
                    entity: { class: UserBundle:User }
        in_memory:
            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    firewalls:
        secured_area:
            pattern:          ^/
            form_login:
                check_path:   /login_check
                login_path:   /login_form
            logout:
                path:         logout
                target:       login_form
            anonymous:        ~
            switch_user:      ~
            remember_me:
                              key: "Order 1138"
    access_control:
                    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
                    - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
                    - { path: ^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
                    - { path: ^/(_wdt|_profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }
                    - { path: ^/, roles: ROLE_USER }
#                   - { path: ^/new, roles: ROLE_USER }
#                   - { path: ^/create, roles: ROLE_USER }
